### PR TITLE
Add AudioFile.h in cmake library interface

### PR DESCRIPTION
**Pull request by alxarsenault**
I added the AudioFile.h to the library, and cleaned up a couple other stuff.

### CODE REVIEW

**Comment by adamstark** [comment]
Thanks for this! I'm really bad at cmake haha, so forgive me if my questions are stupid. Does the moving of the `D_USE_MATH_DEFINES`flag to the `examples` and `tests` CMakeLists.txt files mean that someone on Windows would need to have this as a requirement in their project and would get a build failure otherwise?

**Comment by alxarsenault** [comment]
Before, USE_MATH_DEFINES was added in the main project, so somebody including the project would have a USE_MATH_DEFINES automatically added to their project when including the library. Now it is just added in the examples and tests project so it doesn't affect the library. Make sense ?

**Comment by alxarsenault** [comment]
Sorry, I thought you merged it into develop but finally it was just a 'change base branch from master to develop'

**Comment by adamstark** [comment]
Sorry that it took me so long to review all this properly - and thank you for the contribution. I've just merged it in now :)

**Pull request merged**
