### PR TITLE
Update AudioFile.cpp

### PR DESCRIPTION
**Pull request by edwardkarak**
Replaced the std::cout statements with exceptions, because a library shouldn't display any error messages. 

Fixed bug in load function, where end iterator was not initialized. Introduced rawread function to read the bytes instead.

### CODE REVIEW

**Comment by Sidelobe** [comment]
> Replaced the std::cout statements with exceptions, because a library shouldn't display any error messages.

Please note this is a highly subjective statement, about which many people will disagree for various reasons.

In order to stay with the current "philosophy" of this project (boolean returns, logging of errors), what could be done instead to increase flexibility is to use an output stream for the error messages that can centrally redirected. 

---
On another note, you changed all the indents and operator spacings in your commit which, for one, makes it extremely difficult to review. Also, I believe the etiquette is usually to adjust your coding style to the existing project, not the other way around.

**Comment by edwardkarak** [comment]
> you changed all the indents and operator spacings in your commit which, for one, makes it extremely difficult to review. Also, I believe the etiquette is usually to adjust your coding style to the existing project, not the other way around.

Apologies, I copied and pasted the entire file, with my modifications, from Visual Studio into GitHub. For future reference, how do I copy and paste only the changes I made?

**Comment by Sidelobe** [comment]
> For future reference, how do I copy and paste only the changes I made?

Hmm, that's a tough one... no easy answer for that one. 
In principle I would carefully review my changes 1 by 1 with my Git client or a diff tool and make sure I commit only the changes I want/ought to.

You could also adjust your editor (temporarily?) to match the coding conventions used in the project (indent, operator spacing, bracing, etc...), but then you would have to fiddle with the settings until you match the style (tedious).

Your best best is probably to try and disable any auto-formatting in your editor and never, ever run a 'prettify' or 'format code' and then carefully review your changes before committing.

**Comment by adamstark** [comment]
I've now updated the library so that the logging of error messages to the console is optional. By default they are logged, but you can call..

`audioFile.shouldLogErrorsToConsole (false);`

to switch it off if you don't want that. This is on the develop branch now,

Adam

**Pull request closed without merging**
